### ISSUE TITLE
Signup

### ISSUE THREAD

**Issue by kinhosz** [kinhosz/Wallet-Platform#2]
## Signup Page

A página deve conter três redirects:
- [ ] redirect para página de login, quando o usuário tiver realizado o registro com sucesso.
- [x] redirect para página de erro quando tiver erro 500.
- [x] redirect para a própria página de `signup` quando as constraints do form de registro não forem corretas.

- [x] Quando o usuário preencher alguma informação errada, tal como email ou senha, uma mensagem deve aparecer informando qual foi o erro que o usuário obteve.

- [x] estilização da página: criar a tela com o estilo e fonte que serão aplicadas para toda a identidade visual da plataforma

**Comment by laysearaujo** [comment]
Link: https://www.figma.com/file/mlFi0VQlAyYcvLEK097v0O/Wallet?type=design&node-id=0%3A1&mode=design&t=pW0qjWeZCE8HtpHg-1

**Comment by kinhosz** [comment]
> Link: https://www.figma.com/file/mlFi0VQlAyYcvLEK097v0O/Wallet?type=design&node-id=0%3A1&mode=design&t=pW0qjWeZCE8HtpHg-1

ficou muito bom, eu adorei. Eu só queria adicionar mais 2 pontos:
* qual seria a cor do texto do botão laranja
* se o usuário botar algum dado inválido, a gente vai retornar para essa mesma página e vai botar o erro que ele teve num "popup vermelho" com um botãozinho de x. tu consegue adicionar isso também?

**Comment by laysearaujo** [comment]
Atualizado. Confere os comentários dentro do figma também.

**Comment by kinhosz** [comment]
Estava pensando, a gente realmente vai precisar de um "balão de notificação". Pq essas alterações que tu colocou realmente funcionam, mas só nas validações do lado do client. Se o usuário tiver um erro do lado do servidor, como faz?

**Comment by laysearaujo** [comment]
Feito. Fiz apenas uma notificação padrão de erro no servidor mas caso seja necessário podemos fazer outras com o mesmo estilo.
