### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by kinhosz** [kinhosz/Wallet-Platform#3]
## Login Page

A página deve conter três redirects:
- [ ] redirect para página inicial, quando o usuário tiver realizado o login com sucesso.
- [ ] redirect para página de erro quando tiver erro 500.
- [ ] redirect para a própria página de `login` quando as credenciais não forem corretas.

### Features
- [ ] link para a página de `signup`

**Comment by laysearaujo** [comment]
Baseado na nossa conversa sobre signup, o login ficou assim: https://www.figma.com/design/mlFi0VQlAyYcvLEK097v0O/Wallet?node-id=0%3A1&t=xkqZzwevwtP5RycU-1
